# Generated by Django 6.0.5 on 2026-05-20 15:42

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('social_avatar', models.URLField(blank=True, verbose_name='Аватар из соцсети')),
                ('social_id', models.CharField(blank=True, max_length=255, verbose_name='ID в соцсети')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Провайдер')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('nickname', models.CharField(blank=True, help_text='Имя, которое видят другие пользователи', max_length=150, verbose_name='Отображаемое имя')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите изображение для аватара', null=True, upload_to='users/avatars/%Y/%m/%d/', verbose_name='Аватар (загруженный)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug пользователя')),
                ('is_staff', models.BooleanField(default=False, help_text='Имеет доступ к админ-панели Django', verbose_name='Администратор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
                'indexes': [models.Index(fields=['username', 'nickname'], name='UserApp_use_usernam_6b5b53_idx'), models.Index(fields=['social_id', 'provider'], name='UserApp_use_social__a7ef04_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
