# Generated by Django 6.0.5 on 2026-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Мое резюме', help_text='Например: Python-разработчик', max_length=255, verbose_name='Название резюме')),
                ('text', models.TextField(blank=True, help_text='Полный исходный текст резюме', verbose_name='Текст резюме')),
                ('parsed_skills', models.JSONField(blank=True, default=list, help_text='Ключевые навыки, которые NLP/LLM нашли в исходном тексте', verbose_name='Выделенные навыки из резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Обычное резюме',
                'verbose_name_plural': 'Обычные резюме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Адаптируется'), ('success', 'Успешно готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус адаптации')),
                ('adapted_text', models.TextField(blank=True, verbose_name='Адаптированный текст резюме')),
                ('score_before', models.PositiveIntegerField(blank=True, help_text='Процент совпадения исходного резюме с вакансией', null=True, verbose_name='Совпадение ДО (%)')),
                ('score_after', models.PositiveIntegerField(blank=True, help_text='Процент совпадения после адаптации', null=True, verbose_name='Совпадение ПОСЛЕ (%)')),
                ('changes_log', models.JSONField(blank=True, default=dict, help_text='Данные о том, какие навыки были добавлены или изменены', verbose_name='Лог изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата адаптации')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Адаптированное резюме',
                'verbose_name_plural': 'Адаптированные резюме',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Python-разработчик', max_length=255, verbose_name='Название вакансии')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('description', models.TextField(help_text='Вставленный текст вакансии или результат парсинга', verbose_name='Полное описание вакансии')),
                ('url', models.URLField(blank=True, help_text='Ссылка на hh.ru, LinkedIn и т.д.', verbose_name='Ссылка на вакансию')),
                ('parsed_skills', models.JSONField(blank=True, default=list, help_text='Список ключевых слов и требований, извлеченных из вакансии', verbose_name='Выделенные навыки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
