# Generated by Django 6.0.5 on 2026-05-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
