# Generated by Django 6.0.5 on 2026-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0003_remove_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeadaptation',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', help_text='Язык, на котором будет составлено адаптированное резюме', max_length=2, verbose_name='Язык вывода'),
        ),
    ]
